image: atlassian/default-image:3

pipelines:
  branches:
    develop:
        - step:
            name: Build and publish docker image
            script:
              - IMAGE_NAME=$BITBUCKET_REPO_SLUG
              - DOCKER_BUILDKIT=1 docker build -t ${APP_NAME} -f Dockerfile .
              - docker login --username=_ --password=$HEROKU_TOKEN registry.heroku.com
              - docker tag $APP_NAME registry.heroku.com/$APP_NAME/web
              - docker push registry.heroku.com/$APP_NAME/web
              - docker inspect registry.heroku.com/$APP_NAME/web --format={{.Id}} > WEB_DOCKER_IMAGE_ID
            services:
              - docker
            caches:
              - docker
            artifacts:
              - WEB_DOCKER_IMAGE_ID
        - step:
            name: deploy-to-heroku
            deployment: staging
            script:
              - export WEB_DOCKER_IMAGE_ID=$(cat WEB_DOCKER_IMAGE_ID)
              - chmod +x ./deploy.sh
              - ./deploy.sh
              - echo "Done..."



options:
  docker: true