// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "HOF Engineering",
            "email": "hof.org"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/audio_message": {
            "post": {
                "description": "The endpoint takes an AudioMessageJSON requests and creates a new audio message",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Audio Message"
                ],
                "summary": "Create Audio Message",
                "parameters": [
                    {
                        "description": "create audio message request body",
                        "name": "AudioMessageJSON",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/audio_message.AudioMessageJSON"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/audio_message.AudioMessageJSON"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http_helper.errorResponse"
                        }
                    }
                }
            }
        },
        "/delete/{message_id}": {
            "delete": {
                "description": "The endpoint takes nothing as the request body and update the audio message by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Audio Message"
                ],
                "summary": "Delete Audio Message by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "audio message id",
                        "name": "message_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http_helper.errorResponse"
                        }
                    }
                }
            }
        },
        "/delete/{series_id}": {
            "delete": {
                "description": "The endpoint takes nothing as the request body and update the audio series by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Audio Series"
                ],
                "summary": "Delete Audio Series by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "audio series id",
                        "name": "series_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http_helper.errorResponse"
                        }
                    }
                }
            }
        },
        "/session/forgot_password": {
            "post": {
                "description": "User can request for a password change with the input payload",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sessions"
                ],
                "summary": "User forgets their password",
                "parameters": [
                    {
                        "description": "Forgot password",
                        "name": "ForgotPasswordPayload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.ForgotPasswordPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.ForgotPasswordResponse"
                        }
                    }
                }
            }
        },
        "/session/reset_password/{password_token}": {
            "post": {
                "description": "Creat new password with the input payload",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sessions"
                ],
                "summary": "Rest user password",
                "parameters": [
                    {
                        "description": "Reset password",
                        "name": "ResetPasswordPayload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.ResetPasswordPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http_helper.DefaultResponse"
                        }
                    }
                }
            }
        },
        "/session/sign_in": {
            "post": {
                "description": "Authenticates a user and returns a session",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sessions"
                ],
                "summary": "Create a new session",
                "parameters": [
                    {
                        "description": "Sign in user",
                        "name": "LoginRequestJSON",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.LoginRequestJSON"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.UserSession"
                        }
                    }
                }
            }
        },
        "/session/sign_up": {
            "post": {
                "description": "Creates a new user with the input payload",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sessions"
                ],
                "summary": "Sign up a new user",
                "parameters": [
                    {
                        "description": "Create user",
                        "name": "SignUpUserRequestJSON",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.SignUpUserRequestJSON"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.UserJSON"
                        }
                    }
                }
            }
        },
        "/update/{message_id}": {
            "put": {
                "description": "The endpoint takes an AudioMessageJSON requests and update the audio message",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Audio Message"
                ],
                "summary": "Update Audio Message by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "audio message id",
                        "name": "message_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http_helper.errorResponse"
                        }
                    }
                }
            }
        },
        "/update/{series_id}": {
            "put": {
                "description": "The endpoint takes an AudioSeriesJSON requests and update the audio series",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Audio Series"
                ],
                "summary": "Update Audio Series by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "audio series id",
                        "name": "series_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http_helper.errorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "audio_message.AudioMessageJSON": {
            "type": "object",
            "properties": {
                "audio_url": {
                    "type": "string"
                },
                "author": {
                    "type": "string"
                },
                "date_added": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "image_url": {
                    "type": "string"
                },
                "last_updated": {
                    "type": "string"
                },
                "series_id": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "http_helper.DefaultResponse": {
            "type": "object",
            "properties": {
                "body": {},
                "code": {
                    "type": "integer"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "http_helper.errorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "user.ForgotPasswordPayload": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "description": "The ULID of ForgotPasswordPayload",
                    "type": "string"
                }
            }
        },
        "user.ForgotPasswordResponse": {
            "type": "object",
            "properties": {
                "url": {
                    "type": "string"
                }
            }
        },
        "user.LoginRequestJSON": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "user.ResetPasswordPayload": {
            "type": "object",
            "required": [
                "email",
                "password",
                "password_confirm"
            ],
            "properties": {
                "email": {
                    "description": "The ULID of ResetPasswordPayload",
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "password_confirm": {
                    "type": "string",
                    "minLength": 6
                }
            }
        },
        "user.SignUpUserRequestJSON": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "user.UserJSON": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_verified": {
                    "type": "integer"
                },
                "last_name": {
                    "type": "string"
                },
                "mobile": {
                    "type": "string"
                },
                "newToken": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "user.UserSession": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/user.UserJSON"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/hof",
	Schemes:          []string{},
	Title:            "HOF BACKEND API",
	Description:      "This is the entire doc",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
