basePath: /hof
definitions:
  audio_message.AudioMessageJSON:
    properties:
      audio_url:
        type: string
      author:
        type: string
      date_added:
        type: string
      description:
        type: string
      id:
        type: string
      image_url:
        type: string
      last_updated:
        type: string
      series_id:
        type: string
      title:
        type: string
    type: object
  audio_message.AudioSeriesJSON:
    properties:
      author:
        type: string
      date_added:
        type: string
      description:
        type: string
      id:
        type: string
      image_url:
        type: string
      last_updated:
        type: string
      title:
        type: string
    type: object
  audio_message.GetAudiosMessagesResponse:
    properties:
      audio_messages:
        items:
          $ref: '#/definitions/audio_message.AudioMessageJSON'
        type: array
      pagination:
        $ref: '#/definitions/audio_message.PageResponse'
    type: object
  audio_message.GetAudiosSeriesResponse:
    properties:
      audio_series:
        items:
          $ref: '#/definitions/audio_message.AudioSeriesJSON'
        type: array
      pagination:
        $ref: '#/definitions/audio_message.PageResponse'
    type: object
  audio_message.PageResponse:
    properties:
      totalResults:
        type: integer
    type: object
  http_helper.DefaultResponse:
    properties:
      code:
        type: integer
      message:
        type: string
      success:
        type: boolean
    type: object
  user.ForgotPasswordPayload:
    properties:
      email:
        description: The ULID of ForgotPasswordPayload
        type: string
    required:
    - email
    type: object
  user.ForgotPasswordResponse:
    properties:
      url:
        type: string
    type: object
  user.LoginRequestJSON:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  user.ResetPasswordPayload:
    properties:
      email:
        description: The ULID of ResetPasswordPayload
        type: string
      password:
        minLength: 6
        type: string
      password_confirm:
        minLength: 6
        type: string
    required:
    - email
    - password
    - password_confirm
    type: object
  user.SignUpUserRequestJSON:
    properties:
      email:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      password:
        type: string
    type: object
  user.UserJSON:
    properties:
      address:
        type: string
      email:
        type: string
      first_name:
        type: string
      gender:
        type: string
      id:
        type: string
      is_verified:
        type: integer
      last_name:
        type: string
      mobile:
        type: string
      newToken:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  user.UserSession:
    properties:
      token:
        type: string
      user:
        $ref: '#/definitions/user.UserJSON'
    type: object
host: localhost:3000
info:
  contact:
    email: hof.org
    name: HOF Engineering
  description: This is the entire doc
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: HOF BACKEND API
  version: "1.0"
paths:
  /audio_message:
    get:
      consumes:
      - application/json
      description: Retrieves an audio message
      parameters:
      - description: search message by series id => returns all messages if value
          is * i.e series_id=* or omitted, returns non-series messages if value is
          ? i.e series_id=?
        in: path
        name: series_id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/audio_message.GetAudiosMessagesResponse'
      summary: Get Audio Message
      tags:
      - Audio Message
    post:
      consumes:
      - application/json
      description: The endpoint takes an AudioMessageJSON requests and creates a new
        audio message
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/audio_message.AudioMessageJSON'
      summary: Create Audio Message
      tags:
      - Audio Message
  /audio_message/id/{id}:
    get:
      consumes:
      - application/json
      description: Get Audio Message By ID
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/audio_message.AudioMessageJSON'
      summary: Get Audio Message
      tags:
      - Audio Message
  /audio_series:
    get:
      consumes:
      - application/json
      description: Retrieve an audio series
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/audio_message.GetAudiosSeriesResponse'
      summary: Get an audio series
      tags:
      - Audio Series
    post:
      consumes:
      - application/json
      description: Admin will be able to create/insert new audio series with the input
        payload
      parameters:
      - description: Create audio series
        in: body
        name: AudioSeriesJSON
        required: true
        schema:
          $ref: '#/definitions/audio_message.AudioSeriesJSON'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/audio_message.AudioSeriesJSON'
      summary: Admin can create new audio series
      tags:
      - Audio Series
  /audio_series/id/{id}:
    get:
      consumes:
      - application/json
      description: Get Audio Series By ID
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/audio_message.AudioSeriesJSON'
      summary: Get an audio series
      tags:
      - Audio Series
  /session/forgot_password:
    post:
      consumes:
      - application/json
      description: User can request for a password change with the input payload
      parameters:
      - description: Forgot password
        in: body
        name: ForgotPasswordPayload
        required: true
        schema:
          $ref: '#/definitions/user.ForgotPasswordPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.ForgotPasswordResponse'
      summary: User forgets their password
      tags:
      - Sessions
  /session/reset_password/{password_token}:
    post:
      consumes:
      - application/json
      description: Creat new password with the input payload
      parameters:
      - description: Reset password
        in: body
        name: ResetPasswordPayload
        required: true
        schema:
          $ref: '#/definitions/user.ResetPasswordPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http_helper.DefaultResponse'
      summary: Rest user password
      tags:
      - Sessions
  /session/sign_in:
    post:
      consumes:
      - application/json
      description: Authenticates a user and returns a session
      parameters:
      - description: Sign in user
        in: body
        name: LoginRequestJSON
        required: true
        schema:
          $ref: '#/definitions/user.LoginRequestJSON'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.UserSession'
      summary: Create a new session
      tags:
      - Sessions
  /session/sign_up:
    post:
      consumes:
      - application/json
      description: Creates a new user with the input payload
      parameters:
      - description: Create user
        in: body
        name: SignUpUserRequestJSON
        required: true
        schema:
          $ref: '#/definitions/user.SignUpUserRequestJSON'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.UserJSON'
      summary: Sign up a new user
      tags:
      - Sessions
swagger: "2.0"
