basePath: /hof
definitions:
  FavMessageJSON:
    properties:
      audio_url:
        type: string
      author:
        type: string
      description:
        type: string
      fav:
        type: boolean
      id:
        type: string
      image_url:
        type: string
      message_id:
        type: string
      series_id:
        type: string
      title:
        type: string
      user_id:
        type: string
    type: object
  FavouriteJSON:
    properties:
      date_added:
        type: string
      deleted_at:
        type: string
      fav:
        type: boolean
      id:
        type: string
      message_id:
        type: string
      series_id:
        type: string
      user_id:
        type: string
    type: object
  audio_message.AudioMessageJSON:
    properties:
      audio_url:
        type: string
      author:
        type: string
      date_added:
        type: string
      description:
        type: string
      id:
        type: string
      image_url:
        type: string
      last_updated:
        type: string
      series_id:
        type: string
      title:
        type: string
    type: object
  favourite.GetFavouritesResponse:
    properties:
      favourites:
        items:
          $ref: '#/definitions/FavMessageJSON'
        type: array
      pagination:
        $ref: '#/definitions/favourite.PageResponse'
    type: object
  favourite.PageResponse:
    properties:
      totalResults:
        type: integer
    type: object
  http_helper.DefaultResponse:
    properties:
      body: {}
      code:
        type: integer
      success:
        type: boolean
    type: object
  http_helper.errorResponse:
    properties:
      error:
        type: string
    type: object
  user.ForgotPasswordPayload:
    properties:
      email:
        description: The ULID of ForgotPasswordPayload
        type: string
    required:
    - email
    type: object
  user.ForgotPasswordResponse:
    properties:
      url:
        type: string
    type: object
  user.LoginRequestJSON:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  user.ResetPasswordPayload:
    properties:
      email:
        description: The ULID of ResetPasswordPayload
        type: string
      password:
        minLength: 6
        type: string
      password_confirm:
        minLength: 6
        type: string
    required:
    - email
    - password
    - password_confirm
    type: object
  user.SignUpUserRequestJSON:
    properties:
      email:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      password:
        type: string
    type: object
  user.UserJSON:
    properties:
      address:
        type: string
      email:
        type: string
      first_name:
        type: string
      gender:
        type: string
      id:
        type: string
      is_verified:
        type: integer
      last_name:
        type: string
      mobile:
        type: string
      newToken:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  user.UserSession:
    properties:
      token:
        type: string
      user:
        $ref: '#/definitions/user.UserJSON'
    type: object
host: localhost:3000
info:
  contact:
    email: hof.org
    name: HOF Engineering
  description: This is the entire doc
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: HOF BACKEND API
  version: "1.0"
paths:
  /audio_message:
    post:
      consumes:
      - application/json
      description: The endpoint takes an AudioMessageJSON requests and creates a new
        audio message
      parameters:
      - description: create audio message request body
        in: body
        name: AudioMessageJSON
        required: true
        schema:
          $ref: '#/definitions/audio_message.AudioMessageJSON'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/audio_message.AudioMessageJSON'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http_helper.errorResponse'
      summary: Create Audio Message
      tags:
      - Audio Message
  /delete/{message_id}:
    delete:
      consumes:
      - application/json
      description: The endpoint takes nothing as the request body and update the audio
        message by ID
      parameters:
      - description: audio message id
        in: path
        name: message_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http_helper.errorResponse'
      summary: Delete Audio Message by ID
      tags:
      - Audio Message
  /delete/{series_id}:
    delete:
      consumes:
      - application/json
      description: The endpoint takes nothing as the request body and deletes the
        favourite by ID
      parameters:
      - description: audio series id
        in: path
        name: fav_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http_helper.errorResponse'
      summary: Delete favourite by ID
      tags:
      - Favourites
  /fav:
    post:
      consumes:
      - application/json
      description: The endpoint takes a FavouriteJSON requests and creates a new favourite
      parameters:
      - description: create favourites request body
        in: body
        name: FavouriteJSON
        required: true
        schema:
          $ref: '#/definitions/FavouriteJSON'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/FavouriteJSON'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http_helper.errorResponse'
      summary: Create Favourites
      tags:
      - Favourites
  /favourites:
    get:
      consumes:
      - application/json
      description: Retrieves all favourite/liked messages
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/favourite.GetFavouritesResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http_helper.errorResponse'
      summary: Get Favourites
      tags:
      - Favourites
  /session/forgot_password:
    post:
      consumes:
      - application/json
      description: User can request for a password change with the input payload
      parameters:
      - description: Forgot password
        in: body
        name: ForgotPasswordPayload
        required: true
        schema:
          $ref: '#/definitions/user.ForgotPasswordPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.ForgotPasswordResponse'
      summary: User forgets their password
      tags:
      - Sessions
  /session/reset_password/{password_token}:
    post:
      consumes:
      - application/json
      description: Creat new password with the input payload
      parameters:
      - description: Reset password
        in: body
        name: ResetPasswordPayload
        required: true
        schema:
          $ref: '#/definitions/user.ResetPasswordPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http_helper.DefaultResponse'
      summary: Rest user password
      tags:
      - Sessions
  /session/sign_in:
    post:
      consumes:
      - application/json
      description: Authenticates a user and returns a session
      parameters:
      - description: Sign in user
        in: body
        name: LoginRequestJSON
        required: true
        schema:
          $ref: '#/definitions/user.LoginRequestJSON'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.UserSession'
      summary: Create a new session
      tags:
      - Sessions
  /session/sign_up:
    post:
      consumes:
      - application/json
      description: Creates a new user with the input payload
      parameters:
      - description: Create user
        in: body
        name: SignUpUserRequestJSON
        required: true
        schema:
          $ref: '#/definitions/user.SignUpUserRequestJSON'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.UserJSON'
      summary: Sign up a new user
      tags:
      - Sessions
  /update/{message_id}:
    put:
      consumes:
      - application/json
      description: The endpoint takes an AudioMessageJSON requests and update the
        audio message
      parameters:
      - description: audio message id
        in: path
        name: message_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http_helper.errorResponse'
      summary: Update Audio Message by ID
      tags:
      - Audio Message
  /update/{series_id}:
    put:
      consumes:
      - application/json
      description: The endpoint takes an AudioSeriesJSON requests and update the audio
        series
      parameters:
      - description: audio series id
        in: path
        name: series_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http_helper.errorResponse'
      summary: Update Audio Series by ID
      tags:
      - Audio Series
swagger: "2.0"
