// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "HOF Engineering",
            "email": "hof.org"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/audio_message": {
            "post": {
                "description": "The endpoint takes an AudioMessageJSON requests and creates a new audio message",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Audio Message"
                ],
                "summary": "Create Audio Message",
                "parameters": [
                    {
                        "description": "create audio message request body",
                        "name": "AudioMessageJSON",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/audio_message.AudioMessageJSON"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/audio_message.AudioMessageJSON"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http_helper.errorResponse"
                        }
                    }
                }
            }
        },
        "/delete/{message_id}": {
            "delete": {
                "description": "The endpoint takes nothing as the request body and update the audio message by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Audio Message"
                ],
                "summary": "Delete Audio Message by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "audio message id",
                        "name": "message_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http_helper.errorResponse"
                        }
                    }
                }
            }
        },
        "/delete/{series_id}": {
            "delete": {
                "description": "The endpoint takes nothing as the request body and deletes the favourite by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Favourites"
                ],
                "summary": "Delete favourite by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "message id",
                        "name": "message_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http_helper.errorResponse"
                        }
                    }
                }
            }
        },
        "/fav": {
            "post": {
                "description": "The endpoint takes a FavouriteJSON requests and creates a new favourite",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Favourites"
                ],
                "summary": "Create Favourites",
                "parameters": [
                    {
                        "description": "create favourites request body",
                        "name": "FavouriteJSON",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.FavouriteJSON"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.FavouriteJSON"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http_helper.errorResponse"
                        }
                    }
                }
            }
        },
        "/favourites": {
            "get": {
                "description": "Retrieves all favourite/liked messages",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Favourites"
                ],
                "summary": "Get Favourites",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.GetFavouritesResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http_helper.errorResponse"
                        }
                    }
                }
            }
        },
        "/session/forgot_password": {
            "post": {
                "description": "User can request for a password change with the input payload",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Password"
                ],
                "summary": "User forgets their password",
                "parameters": [
                    {
                        "description": "Forgot password",
                        "name": "ForgotPasswordPayload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.ForgotPasswordPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.OTPResponse"
                        }
                    }
                }
            }
        },
        "/session/sign_in": {
            "post": {
                "description": "Authenticates a user and returns a session",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sessions"
                ],
                "summary": "Create a new session",
                "parameters": [
                    {
                        "description": "Sign in user",
                        "name": "LoginWithDeviceRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.LoginWithDeviceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.UserSession"
                        }
                    }
                }
            }
        },
        "/session/sign_up": {
            "post": {
                "description": "Creates a new user with the input payload",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sessions"
                ],
                "summary": "Signs up a new user",
                "parameters": [
                    {
                        "description": "Create user",
                        "name": "SignUpUserRequestJSON",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.SignUpUserRequestJSON"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.UserJSON"
                        }
                    }
                }
            }
        },
        "/session/verify_token": {
            "post": {
                "description": "The endpoint verifies the OTP input from the user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Password"
                ],
                "summary": "Verify password reset OTP",
                "parameters": [
                    {
                        "description": "Verify OTP",
                        "name": "VerifyOTP",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.VerifyOTP"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.UserSession"
                        }
                    }
                }
            }
        },
        "/update/{message_id}": {
            "put": {
                "description": "The endpoint takes an AudioMessageJSON requests and update the audio message",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Audio Message"
                ],
                "summary": "Update Audio Message by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "audio message id",
                        "name": "message_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http_helper.errorResponse"
                        }
                    }
                }
            }
        },
        "/update/{series_id}": {
            "put": {
                "description": "The endpoint takes an AudioSeriesJSON requests and update the audio series",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Audio Series"
                ],
                "summary": "Update Audio Series by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "audio series id",
                        "name": "series_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http_helper.errorResponse"
                        }
                    }
                }
            }
        },
        "/user/change_password": {
            "post": {
                "description": "Create new password with the input payload",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Password"
                ],
                "summary": "Change user password",
                "parameters": [
                    {
                        "description": "Change password",
                        "name": "ChangePasswordPayload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.ChangePasswordPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http_helper.DefaultResponse"
                        }
                    }
                }
            }
        },
        "/user/reset_password": {
            "post": {
                "description": "Create new password with the input payload",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Password"
                ],
                "summary": "Reset user password",
                "parameters": [
                    {
                        "description": "Reset password",
                        "name": "ResetPasswordPayload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.ResetPasswordPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http_helper.DefaultResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "audio_message.AudioMessageJSON": {
            "type": "object",
            "properties": {
                "audio_url": {
                    "type": "string"
                },
                "author": {
                    "type": "string"
                },
                "date_added": {
                    "type": "string"
                },
                "date_released": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "image_url": {
                    "type": "string"
                },
                "last_updated": {
                    "type": "string"
                },
                "series_id": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "auth.LoginWithDeviceRequest": {
            "type": "object",
            "required": [
                "device_identifier",
                "email",
                "password"
            ],
            "properties": {
                "device_identifier": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "auth.UserSession": {
            "type": "object",
            "properties": {
                "refresh_token": {
                    "type": "string"
                },
                "subscription": {
                    "$ref": "#/definitions/subscription.SubscriptionJSON"
                },
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/user.UserJSON"
                }
            }
        },
        "http_helper.DefaultResponse": {
            "type": "object",
            "properties": {
                "body": {},
                "code": {
                    "type": "integer"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "http_helper.errorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "subscription.SubscriptionJSON": {
            "type": "object",
            "properties": {
                "currency": {
                    "type": "string"
                },
                "fee": {
                    "type": "number"
                },
                "freq": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "next_payment_date": {
                    "type": "string"
                },
                "plan_code": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                },
                "subscription_plan_id": {
                    "type": "string"
                },
                "type": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "user.ChangePasswordPayload": {
            "type": "object",
            "required": [
                "confirm_new_password",
                "email",
                "new_password",
                "old_password"
            ],
            "properties": {
                "confirm_new_password": {
                    "type": "string",
                    "minLength": 6
                },
                "email": {
                    "description": "The ULID of ChangePasswordPayload",
                    "type": "string"
                },
                "new_password": {
                    "type": "string",
                    "minLength": 6
                },
                "old_password": {
                    "type": "string"
                }
            }
        },
        "user.Device": {
            "type": "object",
            "properties": {
                "brand": {
                    "type": "string"
                },
                "dateAdded": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "identifier": {
                    "type": "string"
                },
                "lastUpdated": {
                    "type": "string"
                },
                "os": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/user.DeviceStatus"
                },
                "version": {
                    "type": "string"
                },
                "who": {
                    "type": "string"
                }
            }
        },
        "user.DeviceStatus": {
            "type": "string",
            "enum": [
                "ACTIVE",
                "INACTIVE"
            ],
            "x-enum-varnames": [
                "ACTIVE_DEVICE_STATUS",
                "INACTIVE_DEVICE_STATUS"
            ]
        },
        "user.FavBodyJSON": {
            "type": "object",
            "properties": {
                "date_added": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "fav": {
                    "type": "boolean"
                },
                "message_id": {
                    "type": "string"
                },
                "series_id": {
                    "type": "string"
                }
            }
        },
        "user.FavMessageJSON": {
            "type": "object",
            "properties": {
                "audio_url": {
                    "type": "string"
                },
                "author": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "fav": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "image_url": {
                    "type": "string"
                },
                "message_id": {
                    "type": "string"
                },
                "series_id": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "user.FavouriteJSON": {
            "type": "object",
            "properties": {
                "fav": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/user.FavBodyJSON"
                    }
                },
                "id": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "user.ForgotPasswordPayload": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "description": "The ULID of ForgotPasswordPayload",
                    "type": "string"
                }
            }
        },
        "user.GetFavouritesResponse": {
            "type": "object",
            "properties": {
                "favourites": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/user.FavMessageJSON"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/user.PageResponse"
                }
            }
        },
        "user.OTPResponse": {
            "type": "object",
            "properties": {
                "expireTimeInSeconds": {
                    "type": "integer"
                },
                "otp": {
                    "type": "string"
                },
                "target": {
                    "type": "string"
                }
            }
        },
        "user.PageResponse": {
            "type": "object",
            "properties": {
                "totalResults": {
                    "type": "integer"
                }
            }
        },
        "user.ResetPasswordPayload": {
            "type": "object",
            "required": [
                "email",
                "password",
                "password_confirm"
            ],
            "properties": {
                "email": {
                    "description": "The ULID of ResetPasswordPayload",
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "password_confirm": {
                    "type": "string",
                    "minLength": 6
                }
            }
        },
        "user.SignUpUserRequestJSON": {
            "type": "object",
            "properties": {
                "devices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/user.Device"
                    }
                },
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "user.UserJSON": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "devices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/user.Device"
                    }
                },
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_verified": {
                    "type": "integer"
                },
                "last_name": {
                    "type": "string"
                },
                "latest_app_version": {
                    "$ref": "#/definitions/user.VersionManager"
                },
                "mobile": {
                    "type": "string"
                },
                "newToken": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "user.UserSession": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/user.UserJSON"
                }
            }
        },
        "user.VerifyOTP": {
            "type": "object",
            "properties": {
                "otp": {
                    "type": "string"
                },
                "target": {
                    "type": "string"
                }
            }
        },
        "user.VersionManager": {
            "type": "object",
            "properties": {
                "date_added": {
                    "type": "string"
                },
                "force": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "last_updated": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/hof",
	Schemes:          []string{},
	Title:            "HOF BACKEND API",
	Description:      "This is the entire doc",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
