basePath: /hof
definitions:
  audio_message.AudioMessageJSON:
    properties:
      audio_url:
        type: string
      author:
        type: string
      date_added:
        type: string
      date_released:
        type: string
      description:
        type: string
      id:
        type: string
      image_url:
        type: string
      last_updated:
        type: string
      series_id:
        type: string
      title:
        type: string
    type: object
  auth.LoginWithDeviceRequest:
    properties:
      device_identifier:
        type: string
      email:
        type: string
      password:
        type: string
    required:
    - device_identifier
    - email
    - password
    type: object
  auth.UserSession:
    properties:
      refresh_token:
        type: string
      subscription:
        $ref: '#/definitions/subscription.SubscriptionJSON'
      token:
        type: string
      user:
        $ref: '#/definitions/user.UserJSON'
    type: object
  http_helper.DefaultResponse:
    properties:
      body: {}
      code:
        type: integer
      success:
        type: boolean
    type: object
  http_helper.errorResponse:
    properties:
      error:
        type: string
    type: object
  subscription.SubscriptionJSON:
    properties:
      currency:
        type: string
      fee:
        type: number
      freq:
        type: integer
      id:
        type: string
      next_payment_date:
        type: string
      plan_code:
        type: string
      status:
        type: boolean
      subscription_plan_id:
        type: string
      type:
        type: integer
      user_id:
        type: string
    type: object
  user.ChangePasswordPayload:
    properties:
      confirm_new_password:
        minLength: 6
        type: string
      email:
        description: The ULID of ChangePasswordPayload
        type: string
      new_password:
        minLength: 6
        type: string
      old_password:
        type: string
    required:
    - confirm_new_password
    - email
    - new_password
    - old_password
    type: object
  user.Device:
    properties:
      brand:
        type: string
      dateAdded:
        type: string
      id:
        type: string
      identifier:
        type: string
      lastUpdated:
        type: string
      os:
        type: string
      status:
        $ref: '#/definitions/user.DeviceStatus'
      version:
        type: string
      who:
        type: string
    type: object
  user.DeviceStatus:
    enum:
    - ACTIVE
    - INACTIVE
    type: string
    x-enum-varnames:
    - ACTIVE_DEVICE_STATUS
    - INACTIVE_DEVICE_STATUS
  user.FavBodyJSON:
    properties:
      date_added:
        type: string
      deleted_at:
        type: string
      fav:
        type: boolean
      message_id:
        type: string
      series_id:
        type: string
    type: object
  user.FavMessageJSON:
    properties:
      audio_url:
        type: string
      author:
        type: string
      description:
        type: string
      fav:
        type: boolean
      id:
        type: string
      image_url:
        type: string
      message_id:
        type: string
      series_id:
        type: string
      title:
        type: string
      user_id:
        type: string
    type: object
  user.FavouriteJSON:
    properties:
      fav:
        items:
          $ref: '#/definitions/user.FavBodyJSON'
        type: array
      id:
        type: string
      user_id:
        type: string
    type: object
  user.ForgotPasswordPayload:
    properties:
      email:
        description: The ULID of ForgotPasswordPayload
        type: string
    required:
    - email
    type: object
  user.GetFavouritesResponse:
    properties:
      favourites:
        items:
          $ref: '#/definitions/user.FavMessageJSON'
        type: array
      pagination:
        $ref: '#/definitions/user.PageResponse'
    type: object
  user.OTPResponse:
    properties:
      expireTimeInSeconds:
        type: integer
      otp:
        type: string
      target:
        type: string
    type: object
  user.PageResponse:
    properties:
      totalResults:
        type: integer
    type: object
  user.ResetPasswordPayload:
    properties:
      email:
        description: The ULID of ResetPasswordPayload
        type: string
      password:
        minLength: 6
        type: string
      password_confirm:
        minLength: 6
        type: string
    required:
    - email
    - password
    - password_confirm
    type: object
  user.SignUpUserRequestJSON:
    properties:
      devices:
        items:
          $ref: '#/definitions/user.Device'
        type: array
      email:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      password:
        type: string
    type: object
  user.UserJSON:
    properties:
      address:
        type: string
      devices:
        items:
          $ref: '#/definitions/user.Device'
        type: array
      email:
        type: string
      first_name:
        type: string
      gender:
        type: string
      id:
        type: string
      is_verified:
        type: integer
      last_name:
        type: string
      latest_app_version:
        $ref: '#/definitions/user.VersionManager'
      mobile:
        type: string
      newToken:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  user.UserSession:
    properties:
      token:
        type: string
      user:
        $ref: '#/definitions/user.UserJSON'
    type: object
  user.VerifyOTP:
    properties:
      otp:
        type: string
      target:
        type: string
    type: object
  user.VersionManager:
    properties:
      date_added:
        type: string
      force:
        type: boolean
      id:
        type: string
      last_updated:
        type: string
      version:
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: hof.org
    name: HOF Engineering
  description: This is the entire doc
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: HOF BACKEND API
  version: "1.0"
paths:
  /audio_message:
    post:
      consumes:
      - application/json
      description: The endpoint takes an AudioMessageJSON requests and creates a new
        audio message
      parameters:
      - description: create audio message request body
        in: body
        name: AudioMessageJSON
        required: true
        schema:
          $ref: '#/definitions/audio_message.AudioMessageJSON'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/audio_message.AudioMessageJSON'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http_helper.errorResponse'
      summary: Create Audio Message
      tags:
      - Audio Message
  /delete/{message_id}:
    delete:
      consumes:
      - application/json
      description: The endpoint takes nothing as the request body and update the audio
        message by ID
      parameters:
      - description: audio message id
        in: path
        name: message_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http_helper.errorResponse'
      summary: Delete Audio Message by ID
      tags:
      - Audio Message
  /delete/{series_id}:
    delete:
      consumes:
      - application/json
      description: The endpoint takes nothing as the request body and deletes the
        favourite by ID
      parameters:
      - description: message id
        in: path
        name: message_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http_helper.errorResponse'
      summary: Delete favourite by ID
      tags:
      - Favourites
  /fav:
    post:
      consumes:
      - application/json
      description: The endpoint takes a FavouriteJSON requests and creates a new favourite
      parameters:
      - description: create favourites request body
        in: body
        name: FavouriteJSON
        required: true
        schema:
          $ref: '#/definitions/user.FavouriteJSON'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.FavouriteJSON'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http_helper.errorResponse'
      summary: Create Favourites
      tags:
      - Favourites
  /favourites:
    get:
      consumes:
      - application/json
      description: Retrieves all favourite/liked messages
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.GetFavouritesResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http_helper.errorResponse'
      summary: Get Favourites
      tags:
      - Favourites
  /session/forgot_password:
    post:
      consumes:
      - application/json
      description: User can request for a password change with the input payload
      parameters:
      - description: Forgot password
        in: body
        name: ForgotPasswordPayload
        required: true
        schema:
          $ref: '#/definitions/user.ForgotPasswordPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.OTPResponse'
      summary: User forgets their password
      tags:
      - Password
  /session/sign_in:
    post:
      consumes:
      - application/json
      description: Authenticates a user and returns a session
      parameters:
      - description: Sign in user
        in: body
        name: LoginWithDeviceRequest
        required: true
        schema:
          $ref: '#/definitions/auth.LoginWithDeviceRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.UserSession'
      summary: Create a new session
      tags:
      - Sessions
  /session/sign_up:
    post:
      consumes:
      - application/json
      description: Creates a new user with the input payload
      parameters:
      - description: Create user
        in: body
        name: SignUpUserRequestJSON
        required: true
        schema:
          $ref: '#/definitions/user.SignUpUserRequestJSON'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.UserJSON'
      summary: Signs up a new user
      tags:
      - Sessions
  /session/verify_token:
    post:
      consumes:
      - application/json
      description: The endpoint verifies the OTP input from the user
      parameters:
      - description: Verify OTP
        in: body
        name: VerifyOTP
        required: true
        schema:
          $ref: '#/definitions/user.VerifyOTP'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.UserSession'
      summary: Verify password reset OTP
      tags:
      - Password
  /update/{message_id}:
    put:
      consumes:
      - application/json
      description: The endpoint takes an AudioMessageJSON requests and update the
        audio message
      parameters:
      - description: audio message id
        in: path
        name: message_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http_helper.errorResponse'
      summary: Update Audio Message by ID
      tags:
      - Audio Message
  /update/{series_id}:
    put:
      consumes:
      - application/json
      description: The endpoint takes an AudioSeriesJSON requests and update the audio
        series
      parameters:
      - description: audio series id
        in: path
        name: series_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http_helper.errorResponse'
      summary: Update Audio Series by ID
      tags:
      - Audio Series
  /user/change_password:
    post:
      consumes:
      - application/json
      description: Create new password with the input payload
      parameters:
      - description: Change password
        in: body
        name: ChangePasswordPayload
        required: true
        schema:
          $ref: '#/definitions/user.ChangePasswordPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http_helper.DefaultResponse'
      summary: Change user password
      tags:
      - Password
  /user/reset_password:
    post:
      consumes:
      - application/json
      description: Create new password with the input payload
      parameters:
      - description: Reset password
        in: body
        name: ResetPasswordPayload
        required: true
        schema:
          $ref: '#/definitions/user.ResetPasswordPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http_helper.DefaultResponse'
      summary: Reset user password
      tags:
      - Password
swagger: "2.0"
